<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "skitourenrouten"
 *
 * Auto generated by Extension Builder 2018-11-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Skitouren-Routen',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Hubertus Golf',
    'author_email' => 'info@berti-golf.de',
    'state' => 'beta',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '12.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.0.0-12.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
